### ISSUE TITLE
How to sample for both Normal distribution and Laplace distribition

### ISSUE THREAD

**Issue by weixsong** [axelbrando/Mixture-Density-Networks-for-distribution-and-uncertainty-estimation#4]
Hi, in your validation code, you just use the network output mu to draw the graph, I'm not quite understand this part. I think the "mu" & "sigma" is used to show the range(mu and deviation) of the distribution, is that right?

And, as we need to do sampling from the network output parameters, how could I do sampling both for Normal distribution and Laplace distribution?

Thanks very much.

**Comment by axelbrando** [comment]
Hi Weixsong,

I do not quite see what you mean when you are referring to my "validation code" then, if I do not answer what you need, do not hesitate to ask me again.

Following the explanation that I did in the slides and the Master Thesis, there are different ways to make predictions using MDNs models. For example, you can plot the PDF as a errorbar plot, you can use the parameters that you obtain from the MDN model to do a sampling process, you can plot a heat-map like in the end of the notebook MDN-2D-Regression.ipynb, etc. In all these cases, mu and sigma are used.

Answering your second question, when you implement an MDN model, this mixture has a combination of a certain probabilistic functions. In particular, the cases I have discussed was a mixture of all Gaussians or Laplacians functions but you could define the mixture that interested you (like [here](http://www.cs.toronto.edu/~graves/handwriting.html)). What you should keep in mind is that you are training a neural network to be able to give you the parameters for that predefined mixture and not for any type of PDF.
