### ISSUE TITLE
Version of Keras and Tensorflow

### ISSUE THREAD

**Issue by rashmisankepally** [axelbrando/Mixture-Density-Networks-for-distribution-and-uncertainty-estimation#9]
Please specify which version of Keras and Tensorflow this code is tested on.

**Comment by duhaime** [comment]
@rashmisankepally the README states the versions of Keras (1.1.0) and Tensorflow (0.11.0rc2) used in this project.

It's worth noting that the version of Tensorflow used here is not on PYPI anymore. If you're on OSX, you can install the correct versions of both libraries with:

```bash
# install correct tensorflow version
pip install -U https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc2-py3-none-any.whl

# install correct keras version
pip install -U Keras==1.1.0
```

If this solves your problem, it'd be great if you could close this issue out to tidy things up. If not you could ping me and I'll try to help you...
